language: python

python:
  - "3.6"

install:
- npm i -g npm
- npm install -g allure-commandline

script:
- pip install -r requirements.txt && python -m pytest --alluredir=allure_results -q tests/test_report.py
- ./travis_script/update_allure_results.sh
