language: python
python:
  - "3.6"

install:
  - git clone --depth=50 --branch=master https://github.com/cariel27/pytest_example.git
  - pip install -r pytest_example/requirements.txt
  - npm install -g allure-commandline

script:
  - python -m pytest -q pytest_example/tests/test_report.py